### ISSUE TITLE
removeDefs options is unfalsable

### ISSUE THREAD

**Issue by MikaFima** [meatysolutions/metalsmith-inline-svg#2]
https://github.com/meatysolutions/metalsmith-inline-svg/blob/162edd93b5b894177a76c7b3b386d2bf72544662/lib/index.js#L11

Due to this line, this option can't be `false`.
Using `typeof(xxx) === "undefined"` will be more efficient.

**Comment by timfish** [comment]
Fixed with [your pull request](https://github.com/meatysolutions/metalsmith-inline-svg/pull/1). Thanks for your contributions!

**Comment by timfish** [comment]
0.1.1 published to npm
