### ISSUE TITLE
Issues with paths and other plugins

### ISSUE THREAD

**Issue by MathiasTim** [meatysolutions/metalsmith-inline-svg#4]
hey there, first of all I really love the idea of inlining svgs for production and I really like your approach with the configurable selector.

But I got an issue with my setup.
I am using this plugin: `metalsmith-rootpath` to calculate the correct paths for assets and other stuff.
But when I use this plugin in combination with `metalsmith-inline-svg` I get an error because he cannot find the svg files anymore.
If I swap those two plugins the path is wrong and the svg won't be replaced at all.
It also have to run after the `metalsmith-layouts` plugin otherwise the partials won't be loaded and we I cannot replace the svgs there.

My build setup: 
```js
      var metalsmith = Metalsmith(__dirname)
        .source('src')
        .destination('build')
        .clean(true)
        .use(sass({
          outputStyle: 'compressed'
        }))
        .use(autoprefixer())
        .use(dataMarkdown({
          removeAttributeAfterwards: true
        }))
        .use(i18n({
          default: 'en',
          locales: ['en', 'de'],
          directory: 'locales'
        }))
        .use(multiLanguage({
          default: 'en',
          locales: ['en', 'de']
        }))
        .use(permalinks({
          relative: false,
          pattern: ':locale/:slug/'
        }))
        .use(rootPath())
        .use(layouts({
          engine: 'handlebars',
          partials: 'partials'
        }))
        .use(inlineSVG())
        .use(inPlace({
          directory: 'src',
          pattern: '*.html'
        }))
        .use(htmlMinifier())
        .build((err) => {
          if (err) {
            throw err;
          } else {
            console.log(`Successfully build metalsmith - ${new Date()}`);
          }
        })
``` 

The Error:

```
/Users/mathiasmaier/projects/foobar/index.js:90
            throw err;
            ^

TypeError: Cannot read property 'contents' of undefined
    at Object.<anonymous> (/Users/mathiasmaier/projects/foobar/node_modules/metalsmith-inline-svg/lib/index.js:46:56)
```

But I found the problem:
The paths change during the build process, but the plugin gets them in their original form.
So therefore when a svg should be replaced in `build/foo/bar/index.html` the path changed from `src/assets/some.svg` to `../../some.svg`. Therefore the plugin cannot find this svg.

I made a quickfix to my fork of this project:

https://github.com/MathiasTim/metalsmith-inline-svg/commit/071b15f0ca6c94cdbd502338c187bb569a5ce46b

Question ist: I know its a bit ugly, but is there a better way? What do you think?

**Comment by MathiasTim** [comment]
I just found another plugin which works really great and is also capable for a lot more.

Sorry, I will move to this plugin.

**Comment by joefatora** [comment]
@MathiasTim What is the other plugin? Having similar issues.

**Comment by MathiasTim** [comment]
I used this plugin: https://github.com/alexnewmannn/metalsmith-inline-source

But the useage is a bit different, you can see it in my boilerplate here: https://github.com/MathiasTim/metalsmith-boilerplate
